### ISSUE TITLE
Support for French client

### ISSUE THREAD

**Issue by Eternita-S** [Eternita-S/TextAdvance#1]
In order to make plugin work for French client I need the following strings from the game:
- "Complete" button text when completing a quest
- "Accept" button text when undertaking a new quest
- "Skip cutscene?" confirmation dialogue title
- "Yes." option's text inside skip cutscene confirmation dialogue window.

Please note that text is case-sensitive and punctuation must be included.

**Comment by MKhayle** [comment]
"Complete" button text when completing a quest
![image](https://user-images.githubusercontent.com/4359469/143690435-3e5cfaec-602a-48eb-9ab9-711532fe8967.png)
> `Accepter`


"Accept" button text when undertaking a new quest
![image](https://user-images.githubusercontent.com/4359469/143690348-91780367-d210-483c-b640-6810bec84c36.png)
> `Accepter`


"Skip cutscene?" confirmation dialogue title
![image](https://user-images.githubusercontent.com/4359469/143690574-1a04b018-934a-4fe7-a30a-01522990c954.png)
> `Passer la scène cinématique ?`

"Yes." option's text inside skip cutscene confirmation dialogue window.
> `Oui`

**Comment by Eternita-S** [comment]
Thank you for help! I have added these strings in latest update, please test if everything works properly.

**Comment by MKhayle** [comment]
Confirming it's working perfectly, thank you !
