### ISSUE TITLE
Cannot Disable Auto Quest Accept

### ISSUE THREAD

**Issue by atakocabas** [Eternita-S/TextAdvance#13]
Simply, it does not work. 3 of my friends has the same problem as well. I hope, we are not doing anything wrong.

**Comment by Eternita-S** [comment]
could you attach your configuration file that is located at `%appdata%\XIVLauncher\pluginConfigs\TextAdvance.json`?

**Comment by atakocabas** [comment]
[TextAdvance.zip](https://github.com/Eternita-S/TextAdvance/files/9126702/TextAdvance.zip)
MainConfig part is right, I suppose but still I do not understand why it does not work. Thank you in advance!

**Comment by Eternita-S** [comment]
There was a bug. It should be fixed in the 3.0.0.1 update, let me know if it works after updating the plugin through plugin installer.

**Comment by atakocabas** [comment]
Oh, I updated and it works perfectly now. Thanks
