### ISSUE TITLE
Support for Japanese client

### ISSUE THREAD

**Issue by Eternita-S** [Eternita-S/TextAdvance#3]
In order to make plugin work for Japanese client I need the following strings from the game:
- "Complete" button text when completing a quest
- "Accept" button text when undertaking a new quest
- "Skip cutscene?" confirmation dialogue title
- "Yes." option's text inside skip cutscene confirmation dialogue window.

Please note that text is case-sensitive and punctuation must be included.

**Comment by Rigaln** [comment]
- コンプリート
- 受注
- このカットシーンをスキップしますか？
- はい
From top to bottom.
Please let me know if I'm missing anything or if I'm wrong.

**Comment by Eternita-S** [comment]
Hello! Thank you, added it. Let me know if it works.
