### ISSUE TITLE
Requesting Support For Chinese Client

### ISSUE THREAD

**Issue by NicoOrz** [Eternita-S/TextAdvance#4]
"Complete" button text when completing a quest
"Accept" button text when undertaking a new quest
"Skip cutscene?" confirmation dialogue title
"Yes." option's text inside skip cutscene confirmation dialogue window.
"Complete" = "完成“
“Accept”=“接受”
”Skip cutscene?"="要跳过这段过场动画吗？”
"Yes."="是“

**Comment by Eternita-S** [comment]
Hello!
An Endwalker update has been released to global game, therefore I'll update TextAdvance.
However I have kept current version in this custom repo, if needed: `https://raw.githubusercontent.com/Eternita-S/MyDalamudPlugins/main/API4/api4pluginmaster.json`
